### ISSUE TITLE
New release for use with 2.12?

### ISSUE THREAD

**Issue by andreak** [dchenbecker/scalajpa#9]
Are the 2.12 related changes good for release?
Whould be nice to have this in maven by the time for Lift-3 for 2.12.

**Comment by dchenbecker** [comment]
Darnit, I forgot to release the staged artifact. I'll take care of that right now.

**Comment by dchenbecker** [comment]
It's released. Please let me know if you have any further issues with it.

**Comment by andreak** [comment]
Great, thanks!
